### PR TITLE
moved auth to sessionStore

### PR DESCRIPTION
**Pull request by vuzDylan**
Moved token storage to session and added ability to check if use is already authed

### CODE REVIEW

**Comment by vuzDylan** [comment]
linter seems to be busted

**Comment by kristenmills** [comment]
Merge master into better-auth and the linter will no longer be busted.

**Comment by vuzDylan** [comment]
its already up todate

**Comment by kristenmills** [comment]
No it isn't. I promise you it isn't

**Comment by vuzDylan** [comment]
just ran git pull master, git merge master and git rebase master and nothing happned

**Comment by kristenmills** [comment]
Well I just merged in 2 commits from master to your so called "up to date" branch. And fixed the build. So.

**Comment by vuzDylan** [comment]
what how

**Comment by kristenmills** [comment]
Because you really weren't up to date with master. Now fix your lint errors.

**Comment by vuzDylan** [comment]
oh im stupid
i wan't in the right repo

**Comment by vuzDylan** [comment]
*Fixed*

**Comment by vuzDylan** [comment]
when this merges does the NPM thing happen auto magicly?

**Comment by kristenmills** [comment]
It's not actually published to npm. We install via git repo

**Comment by vuzDylan** [comment]
I thought it was published? anyway is there a better way to do that or is the stupid var self = this; the only solution

**Comment by vuzDylan** [comment]
I kind of want it to return a promise that just rejects if the token is invalid... thoughts?

**Comment by kristenmills** [comment]
Not in es5. And yeah you can do that.

**Pull request merged**
